Add Zahlen Raten
Koch-Dustin/Zahlenraten pull request #1
Opened 2022-11-15 11:48 UTC by Koch-Dustin

Changes:
   - Add Zahlen Raten

2022-11-15 12:23 UTC, DevBastiS commented on main.py
> +  print("Ich denke an eine Zahl zwischen 1 - 20. Kannst du sie erraten?")
That is a lie ;)

2022-11-15 12:23 UTC, DevBastiS commented on main.py
> +  userGuessedNumber = -1
Why not 0?

2022-11-15 12:23 UTC, DevBastiS commented on main.py
> +    else:
You can use early exit here ;)

2022-11-15 12:23 UTC, DevBastiS approved these changes

2022-11-16 07:37 UTC, DevBastiS approved these changes

2022-11-21 08:12 UTC, MKrips requested changes

2022-11-21 08:12 UTC, MKrips commented on main.py
> +  trysTakeToGuess = 0
```suggestion
  triesNeededToGuess = 0
```

2022-11-22 12:11 UTC, Koch-Dustin commented on main.py
> +    else:
When i implement "break" it prints out the wanted message and then it stops running the file

2022-11-22 15:02 UTC, MKrips approved these changes

2022-11-25 09:09 UTC, merged